---
title: "Code Chunks"
author: "Paloma B. Lopes"
affilitation: "JHU"
date: today
format: 
  html:
    theme: 
      light: minty
      dark: superhero
    toc: true
    toc-title: Contents
    toc-location: right
    number-sections: true 
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 400px
      gutter-width: 1.5rem
self-contained: true
lang: en   
bibliography: bibby.bib
reference-location: margin
citation-location: margin
execute:
  echo: false
---

@lst-default - presents the default settings of the code chunks

```{r}
#| echo: true
#| lst-label: lst-default
#| lst-cap: Default settings
head(cars)
```

```{r}
#| echo: false
#| lst-label: lst-echoF
#| lst-cap: Echo FALSE
head(cars)
```

```{r}
#| echo: true
#| eval: false
#| lst-label: lst-echoF
#| lst-cap: Echo TRUE, EVAL FALSE
head(cars)
```

```{r}
#| label: fig-normal
#| fig-cap: A normal distribution
x = seq(-3,3, length.out = 10000)
dx = dnorm(x)
plot(x,dx,type = "l", cex = 2, lwd =3)
```

@fig-normalProperties illustrates properties. @fig-normalProperties-1,  @fig-normalProperties-2, and  @fig-normalProperties-3, 

```{r}
#| layout-ncol: 3
#| label: fig-normalProperties
#| fig-cap: A normal distribution
#| fig-subcap:
#|  - "Density"
#|  - "Cumulative"
#|  - "Quantile"
x = seq(-3,3, length.out = 10000)
dx = dnorm(x)
plot(x,dx,type = "l", cex = 2, lwd =3)
plot(x,pnorm(x),type = "l", cex = 2, lwd =3)
plot(pnorm(x), qnorm(pnorm(x)),type = "l", cex = 2, lwd =3)
```






